language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "nightly"
  allow_failures:
    - python: "nightly"

# commands to run tests
script:
  coverage run --omit=evee/abstract_event_dispatcher.py,evee/abstract_event_subscriber.py --source=evee setup.py test
after_success:
  python-codacy-coverage -r coverage.xml
