language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

# command to install dependencies
install:
  - pip install codacy-coverage coverage
# commands to run tests
script:
  coverage run --source=evee setup.py test
  coverage xml
after_success:
  python-codacy-coverage -r coverage.xml
